version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  app:
    build: .
    container_name: app
    ports:
      - '8080:8080'
    environment:
      - MONGO_DB_URI=mongodb://root:password@mongodb:27017
    depends_on: 
      - mongodb
volumes:
  mongodb_data:
